str1 = "Selenium is a free (open-source) automated testing framework used to validate web applications across different browsers and platforms. You can use multiple programming languages like Java, C#, Python, etc to create Selenium Test Scripts. Testing done using the Selenium testing tool is usually referred to as Selenium Testing."
print(str1[::-1])
print(str1[2])
print(str1[0:8])
print(str1[-1])
print(str1[::1])
print(str1[0:])
print(str1[-6:-1])
print(str1[-10:])
print(str1.find("Selenium"))
print(str1.find("automated"))
print(str1[33:50])